import { StyleSheet } from 'react-native';
import { Dimensions } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    display: 'flex',
    backgroundColor: 'black',
    opacity: 0.95,
  },
  mapContainer: {
    height: Dimensions.get('window').height - 340,
  },
  driverCard: {
    flexDirection: 'row',
    flex: 1,
    borderBottomWidth: 0.7,
    borderBottomColor: '#5d5d5d',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5, // Android shadow
  },
  image: {
    height: 70,
    width: 80,
    resizeMode: 'contain',
    borderRadius: 20,
    marginRight: 30,
    marginLeft: 5,
    borderWidth: 2,
    borderColor: '#5d5d5d', // subtle border to add elegance
  },
  carContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    justifyContent: 'space-between',
  },
  carDetails: {
    fontSize: 14,
    marginBottom: 5,
    color: 'white',
    fontFamily: 'Manrope-SemiBold',
  },
  driverName: {
    fontSize: 12,
    color: 'white',
    fontFamily: 'Manrope-SemiBold',
    textTransform: 'uppercase',
  },
  type: {
    fontSize: 15,
    marginBottom: 5,
    color: 'white',
    marginTop: 10,
    fontFamily: 'Manrope-SemiBold',
  },
  time: {
    color: '#7a7a7a',
    fontFamily: 'Manrope-SemiBold',
  },
  rightContainer: {
    left: 155,
    bottom: 30,
    fontFamily: 'Manrope-SemiBold',
  },
  price: {
    fontSize: 16,
    color: 'white',
    fontFamily: 'Manrope-SemiBold',
    textShadowColor: '#000',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  carListContainer: {
    flex: 1,
    marginBottom: 30,
  },
  heading: {
    backgroundColor: '#2a2a2a',
    borderWidth: 1.5,
    borderColor: '#8a8a8a',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  headingText: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 10,
    color: 'white',
    textShadowColor: 'black',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 15,
  },
  buttonRow: {
    position: 'absolute',
    bottom: 15,
    left: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reloadBtn: {
    backgroundColor: '#43b0f1',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  confirmBtn: {
    backgroundColor: '#2a2a2a',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 66,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  backButton: {
    backgroundColor: '#2a2a2a',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    width: 40,
    borderWidth: 0.8,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  reloadBtn: {
    backgroundColor: '#2a2a2a',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    width: 40,
    borderWidth: 0.8,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  confirmBtnText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Manrope-Bold',
  },
  loadingText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Manrope-Bold',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 20
  },
  fixedCategoryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 1,
    backgroundColor: 'black',
    padding: 5,
  },
  categoryBox: {
    backgroundColor: 'black',
    paddingHorizontal: 17,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#5c5c5c',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  selectedCategory: {
    backgroundColor: '#43b0f1',
  },
  categoryText: {
    fontSize: 16,
    color: 'white',
    textAlign: 'center',
  },
  confirmBtnText: {
    color: 'white',
    fontFamily: 'Manrope-Bold',
    fontSize: 16,
  },
});

export default styles;
